name: Build Check

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    working-directory: frontend/
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build web application
        run: npm run build
